import { createContext, useContext, useState, useEffect } from 'react';

const THEMES = {
  cameroun: {
    id: 'cameroun',
    icon: '🇨🇲',
    name: '🇨🇲 Cameroun',
    primary: '#E63946',
    secondary: '#FF9F1C',
    accent: '#2DC653',
    bg: '#F0F2F8',
    card: '#FFFFFF',
    text: '#1A1A2E',
    subtext: '#888888',
    border: '#EEEEEE',
    inputBg: '#F8F9FF',
    navBg: '#FFFFFF',
    gradient: 'linear-gradient(160deg,#E63946 0%,#FF9F1C 45%,#2DC653 100%)',
    dark: false,
  },
  ocean: {
    id: 'ocean',
    icon: '🌊',
    name: '🌊 Ocean',
    primary: '#0077B6',
    secondary: '#00B4D8',
    accent: '#90E0EF',
    bg: '#EBF8FF',
    card: '#FFFFFF',
    text: '#03045E',
    subtext: '#6B7280',
    border: '#BFDBFE',
    inputBg: '#F0F9FF',
    navBg: '#FFFFFF',
    gradient: 'linear-gradient(160deg,#03045E 0%,#0077B6 50%,#00B4D8 100%)',
    dark: false,
  },
  midnight: {
    id: 'midnight',
    icon: '🌙',
    name: '🌙 Midnight',
    primary: '#7C3AED',
    secondary: '#F59E0B',
    accent: '#10B981',
    bg: '#0F0F1A',
    card: '#1E1E2E',
    text: '#FFFFFF',
    subtext: '#9CA3AF',
    border: '#2E2E3E',
    inputBg: '#2A2A3A',
    navBg: '#1A1A2A',
    gradient: 'linear-gradient(160deg,#0F0F1A 0%,#7C3AED 60%,#F59E0B 100%)',
    dark: true,
  },
  nature: {
    id: 'nature',
    icon: '🌿',
    name: '🌿 Nature',
    primary: '#2D6A4F',
    secondary: '#74C69D',
    accent: '#B7E4C7',
    bg: '#F0F7F4',
    card: '#FFFFFF',
    text: '#1B4332',
    subtext: '#6B7280',
    border: '#D8F3DC',
    inputBg: '#F0FDF4',
    navBg: '#FFFFFF',
    gradient: 'linear-gradient(160deg,#1B4332 0%,#2D6A4F 50%,#74C69D 100%)',
    dark: false,
  },
  sunset: {
    id: 'sunset',
    icon: '🔥',
    name: '🔥 Sunset',
    primary: '#F97316',
    secondary: '#EC4899',
    accent: '#FCD34D',
    bg: '#FFF7ED',
    card: '#FFFFFF',
    text: '#7C2D12',
    subtext: '#9A3412',
    border: '#FED7AA',
    inputBg: '#FFF7F0',
    navBg: '#FFFFFF',
    gradient: 'linear-gradient(160deg,#7C2D12 0%,#F97316 50%,#EC4899 100%)',
    dark: false,
  },
  royal: {
    id: 'royal',
    icon: '💎',
    name: '💎 Royal',
    primary: '#1E3A8A',
    secondary: '#D97706',
    accent: '#6B7280',
    bg: '#EFF6FF',
    card: '#FFFFFF',
    text: '#1E1B4B',
    subtext: '#6B7280',
    border: '#DBEAFE',
    inputBg: '#F5F3FF',
    navBg: '#FFFFFF',
    gradient: 'linear-gradient(160deg,#1E1B4B 0%,#1E3A8A 50%,#D97706 100%)',
    dark: false,
  },
  grape: {
    id: 'grape',
    icon: '🍇',
    name: '🍇 Grape',
    primary: '#7E22CE',
    secondary: '#A78BFA',
    accent: '#DDD6FE',
    bg: '#FAF5FF',
    card: '#FFFFFF',
    text: '#3B0764',
    subtext: '#7C3AED',
    border: '#EDE9FE',
    inputBg: '#FAF5FF',
    navBg: '#FFFFFF',
    gradient: 'linear-gradient(160deg,#3B0764 0%,#7E22CE 50%,#A78BFA 100%)',
    dark: false,
  },
  carbon: {
    id: 'carbon',
    icon: '⚫',
    name: '⚫ Carbon',
    primary: '#22C55E',
    secondary: '#4ADE80',
    accent: '#86EFAC',
    bg: '#030712',
    card: '#111827',
    text: '#F9FAFB',
    subtext: '#9CA3AF',
    border: '#1F2937',
    inputBg: '#1F2937',
    navBg: '#111827',
    gradient: 'linear-gradient(160deg,#030712 0%,#111827 50%,#22C55E 100%)',
    dark: true,
  },
};

export const T = {
  fr: {
    home:"Accueil", members:"Membres", participation:"Participation", chat:"Chat",
    aid:"Aide", history:"Historique", admin:"Admin", settings:"Paramètres",
    stats:"Stats", polls:"Sondages", profile:"Profil",
    totalBalance:"SOLDE TOTAL", cotised:"membres ont cotisé", deposit:"Dépôt",
    rules:"Règles", readApproved:"Lu et approuvé ✅",
    whoEats:"QUI BOUFFE CETTE SEMAINE", next:"PROCHAIN BÉNÉFICIAIRE",
    aidOngoing:"AIDE EN COURS", rotationCal:"Calendrier de rotation",
    inProgress:"EN COURS", upcoming:"À venir",
    addMember:"+ Ajouter", newMember:"Nouveau membre", fullName:"Nom complet",
    phone:"Téléphone", inviteLink:"Lien d'invitation",
    confirm:"✅ Ajouter", cancel:"Annuler", remove:"Retirer", position:"Position",
    penalized:"⚠️ Pénalisé", consultOnly:"👁️ Mode consultation",
    currentBalance:"SOLDE ACTUEL", cotised2:"COTISÉ",
    penalty:"Pénalité", writeMsg:"Écrire un message...",
    recording:"Enregistrement...", send:"✅ Envoyer",
    noAid:"Aucune aide en cours", createAid:"+ Créer une aide",
    aidTitle:"Intitulé de l'aide", aidDesc:"Description", aidDeadline:"Date limite",
    objective:"Objectif (FCFA)", create:"Créer", contributions:"Contributions",
    exportPdf:"📄 Exporter en PDF", allFilter:"Tout", cotisations:"Cotisations",
    penalties:"Pénalités", beneficiaries:"Bénéficiaires", aids:"Aides",
    administrators:"Administrateurs", superAdmin:"👑 Super Admin",
    addAdmin:"+ Ajouter un administrateur", adminInviteLink:"Code invitation admin",
    singleUse:"⚠️ Usage unique · Expire dans 24h",
    myTontines:"Mes tontines", newTontine:"+ Nouvelle tontine",
    cotisationFreq:"Cotisation & Fréquence", amount:"Montant (FCFA)",
    frequency:"Fréquence", startDate:"Date de début", depositPhone:"N° de dépôt",
    weekly:"Hebdo", biweekly:"2 sem.", monthly:"Mensuel", bimonthly:"2 mois",
    penaltyAmount:"Montant pénalité (FCFA)", autoPenalty:"Pénalité automatique",
    tontineRules:"Règles de la tontine", save:"💾 Enregistrer",
    dangerZone:"Zone dangereuse", deleteTitle:"Supprimer cette tontine",
    deleteWarning:"Action irréversible. Toutes les données seront perdues.",
    delete:"Supprimer", language:"Langue", becomeAdmin:"Devenir administrateur",
    becomeAdminInfo:"Entrez le code fourni par un administrateur.",
    adminCode:"Code admin", validate:"Valider", logout:"🚪 Déconnexion",
    aidToggle:"Activer l'onglet Aide", darkMode:"Mode sombre",
    reminders:"Rappels automatiques",
    login:"Connexion", register:"S'inscrire", email:"Email", password:"Mot de passe",
    iAm:"Je suis :", administrator:"👑 Administrateur", member:"👤 Membre",
    connect:"Se connecter 🚀", createAccount:"Créer mon compte ✨",
    forgotPassword:"Mot de passe oublié ?", forgotTitle:"Mot de passe oublié",
    forgotSub:"Un lien de réinitialisation sera envoyé à votre email",
    sendLink:"Envoyer le lien 📧", linkSent:"Lien envoyé !",
    checkEmail:"Vérifiez votre boîte email.", backToLogin:"Retour à la connexion",
    back:"Retour", memberWarning:"⚠️ Inscription membre via lien d'invitation uniquement.",
    participationRate:"Taux de participation", topMembers:"Membres les plus assidus",
    balanceEvolution:"Évolution du solde", cycleProgress:"Progression des cycles",
    cycle:"Cycle", of:"sur", createPoll:"+ Créer un sondage",
    pollQuestion:"Question", pollOption:"Option", addOption:"+ Ajouter option",
    vote:"Voter", voted:"✅ Voté", pinnedMsg:"Message épinglé",
    pin:"📌 Épingler", unpin:"Désépingler",
    receiptTitle:"Reçu de cotisation",
    editProfile:"Modifier le profil", displayName:"Nom d'affichage",
    saveProfile:"Enregistrer le profil", noPolls:"Aucun sondage en cours",
    totalCycles:"Nombre total de cycles", deleteAccount:"🗑️ Supprimer mon compte",
    deleteAccountWarning:"Cette action est irréversible. Toutes vos données seront supprimées.",
    confirmDelete:"Confirmer la suppression",
    tontineName:"Nom de la tontine", createTontine:"Créer la tontine",
    noTontine:"Vous n'êtes dans aucune tontine",
    rulesAcceptRequired:"Veuillez lire et accepter les règles pour continuer",
    inviteCode:"Code d'invitation", joinTontine:"Rejoindre la tontine",
    error:"Erreur", success:"Succès", loading:"Chargement...", pinned:"Épinglé",
    theme:"Thème", chooseTheme:"Choisissez votre thème",
    applyTheme:"Appliquer ce thème", themeApplied:"Thème appliqué !",
    aboutApp:"À propos",
  },
  en: {
    home:"Home", members:"Members", participation:"Participation", chat:"Chat",
    aid:"Aid", history:"History", admin:"Admin", settings:"Settings",
    stats:"Stats", polls:"Polls", profile:"Profile",
    totalBalance:"TOTAL BALANCE", cotised:"members contributed", deposit:"Deposit",
    rules:"Rules", readApproved:"Read and approved ✅",
    whoEats:"WHO GETS PAID THIS WEEK", next:"NEXT BENEFICIARY",
    aidOngoing:"ONGOING AID", rotationCal:"Rotation Calendar",
    inProgress:"IN PROGRESS", upcoming:"Upcoming",
    addMember:"+ Add", newMember:"New member", fullName:"Full name",
    phone:"Phone", inviteLink:"Invitation link",
    confirm:"✅ Add", cancel:"Cancel", remove:"Remove", position:"Position",
    penalized:"⚠️ Penalized", consultOnly:"👁️ View only",
    currentBalance:"CURRENT BALANCE", cotised2:"PAID",
    penalty:"Penalty", writeMsg:"Write a message...",
    recording:"Recording...", send:"✅ Send",
    noAid:"No ongoing aid", createAid:"+ Create aid",
    aidTitle:"Aid title", aidDesc:"Description", aidDeadline:"Deadline",
    objective:"Objective (FCFA)", create:"Create", contributions:"Contributions",
    exportPdf:"📄 Export PDF", allFilter:"All", cotisations:"Contributions",
    penalties:"Penalties", beneficiaries:"Beneficiaries", aids:"Aid",
    administrators:"Administrators", superAdmin:"👑 Super Admin",
    addAdmin:"+ Add administrator", adminInviteLink:"Admin invite code",
    singleUse:"⚠️ Single use · Expires in 24h",
    myTontines:"My tontines", newTontine:"+ New tontine",
    cotisationFreq:"Contribution & Frequency", amount:"Amount (FCFA)",
    frequency:"Frequency", startDate:"Start date", depositPhone:"Deposit phone",
    weekly:"Weekly", biweekly:"2 weeks", monthly:"Monthly", bimonthly:"2 months",
    penaltyAmount:"Penalty amount (FCFA)", autoPenalty:"Automatic penalty",
    tontineRules:"Tontine rules", save:"💾 Save",
    dangerZone:"Danger zone", deleteTitle:"Delete this tontine",
    deleteWarning:"Irreversible action. All data will be lost.",
    delete:"Delete", language:"Language", becomeAdmin:"Become administrator",
    becomeAdminInfo:"Enter the code provided by an administrator.",
    adminCode:"Admin code", validate:"Validate", logout:"🚪 Log out",
    aidToggle:"Enable Aid tab", darkMode:"Dark mode",
    reminders:"Automatic reminders",
    login:"Login", register:"Sign up", email:"Email", password:"Password",
    iAm:"I am:", administrator:"👑 Administrator", member:"👤 Member",
    connect:"Log in 🚀", createAccount:"Create account ✨",
    forgotPassword:"Forgot password?", forgotTitle:"Forgot password",
    forgotSub:"A reset link will be sent to your email",
    sendLink:"Send link 📧", linkSent:"Link sent!",
    checkEmail:"Check your inbox.", backToLogin:"Back to login",
    back:"Back", memberWarning:"⚠️ Member registration requires an invitation link.",
    participationRate:"Participation rate", topMembers:"Most active members",
    balanceEvolution:"Balance evolution", cycleProgress:"Cycle progress",
    cycle:"Cycle", of:"of", createPoll:"+ Create poll",
    pollQuestion:"Question", pollOption:"Option", addOption:"+ Add option",
    vote:"Vote", voted:"✅ Voted", pinnedMsg:"Pinned message",
    pin:"📌 Pin", unpin:"Unpin",
    receiptTitle:"Contribution receipt",
    editProfile:"Edit profile", displayName:"Display name",
    saveProfile:"Save profile", noPolls:"No active polls",
    totalCycles:"Total cycles", deleteAccount:"🗑️ Delete my account",
    deleteAccountWarning:"This action is irreversible. All your data will be deleted.",
    confirmDelete:"Confirm deletion",
    tontineName:"Tontine name", createTontine:"Create tontine",
    noTontine:"You are not in any tontine",
    rulesAcceptRequired:"Please read and accept the rules to continue",
    inviteCode:"Invitation code", joinTontine:"Join tontine",
    error:"Error", success:"Success", loading:"Loading...", pinned:"Pinned",
    theme:"Theme", chooseTheme:"Choose your theme",
    applyTheme:"Apply theme", themeApplied:"Theme applied!",
    aboutApp:"About",
  }
};

const ThemeContext = createContext();

export function ThemeProvider({ children }) {
  const [themeId, setThemeId] = useState(() => localStorage.getItem('ts_theme') || 'cameroun');
  const [lang, setLang] = useState(() => localStorage.getItem('ts_lang') || 'fr');

  const theme = THEMES[themeId] || THEMES.cameroun;
  const C = theme;
  const t = T[lang];

  const applyTheme = (id) => {
    setThemeId(id);
    localStorage.setItem('ts_theme', id);
  };

  const changeLang = (l) => {
    setLang(l);
    localStorage.setItem('ts_lang', l);
  };

  return (
    <ThemeContext.Provider value={{
      theme, themeId, applyTheme, THEMES,
      lang, setLang: changeLang,
      C, t,
      darkMode: theme.dark,
    }}>
      <div style={{ background: C.bg, minHeight: '100vh', transition: 'all 0.3s' }}>
        {children}
      </div>
    </ThemeContext.Provider>
  );
}

export const useTheme = () => useContext(ThemeContext);
